USE hr;

# Truy vấn 1
SELECT  *
FROM    EMPLOYEES
WHERE   `ADDRESS` LIKE '%Elgin,IL';

# Truy vấn 2
SELECT  *
FROM    EMPLOYEES
WHERE   B_DATE LIKE '197%';

# Truy vấn 3
SELECT  *
FROM    EMPLOYEES
WHERE   DEP_ID = 5 AND (SALARY BETWEEN 60000 AND 70000);

# Truy vấn 4A
SELECT      *
FROM        EMPLOYEES
ORDER BY    DEP_ID;

# Truy vấn 4B
SELECT      *
FROM        EMPLOYEES 
ORDER BY    DEP_ID DESC, L_NAME DESC;

# Truy vấn 5A
SELECT      COUNT(EMP_ID), DEP_ID
FROM        EMPLOYEES
GROUP BY    DEP_ID;

# Truy vấn 5B
SELECT      COUNT(EMP_ID), DEP_ID, AVG(SALARY)
FROM        EMPLOYEES
GROUP BY    DEP_ID;

# Truy vấn 5C
SELECT      COUNT(EMP_ID) AS NUM_EMPLOYEES, DEP_ID, AVG(SALARY) AS AVG_SALARY
FROM        EMPLOYEES
GROUP BY    DEP_ID;

# Truy vấn 5D
SELECT      COUNT(EMP_ID) AS NUM_EMPLOYEES, DEP_ID, AVG(SALARY) AS AVG_SALARY
FROM        EMPLOYEES
GROUP BY    DEP_ID
ORDER BY    AVG(SALARY);

# Truy vấn 5E
SELECT      COUNT(EMP_ID) AS NUM_EMPLOYEES, DEP_ID, AVG(SALARY) AS AVG_SALARY
FROM        EMPLOYEES
GROUP BY    DEP_ID
HAVING      COUNT(EMP_ID) < 4
ORDER BY    AVG(SALARY);